### ISSUE TITLE
Embedding operation dashboard into the story map (tabbed)

### ISSUE THREAD

**Issue by Nataliya1** [Esri/dashboard-samples#3]
I am trying to embed an operation dashboard app (web version) into a story map (Map Series - Tabbed), but it just would not show up. The operation dashboard is shared with everyone, and so is story map. Not sure why it would not load? Any help is greatly appreciated. Thank you. Nataliya

**Comment by christopherolsen** [comment]
Issue was that user had a problem between http and https in the embedded maps.  Once that was cleared up, the issue was resolved. (per https://github.com/Esri/map-series-storytelling-template-js/issues/27)

**Comment by AkothCarole** [comment]
@christopherolsen How was this cleared? I seem to have the same issue

**Comment by ffaubry** [comment]
@AkothCarole Are you using the legacy Dashboard or are you using the lates Dashboard Online or are you using a Dashboard as part of ArcGIS Enterprise?

Please see the README for the deprecation note: https://github.com/Esri/dashboard-samples/blob/master/README.md
