### ISSUE TITLE
Last update to Dashboard render configuration pane blank 

### ISSUE THREAD

**Issue by steffenph** [Esri/dashboard-samples#6]
Hi,

I have used these samples with great success in the past, but after the last update of the Dashboard app (windows) both my own widgets and the samples in this repo are not functioning correctly. I'm not seeing the configuration page of any widgets, just a blank page. The debug console does not provide any information either. Is this behaviour known? It may be a user error of course. Thanks.

**Comment by jaychen15-zz** [comment]
Hi @steffenph - did you see this issue only for configuration of the widget or everything about the widget? Does the widget itself load correctly?

**Comment by steffenph** [comment]
It seems like this issue is both for the configuration and for the display of the widget. Using the URLs from the debug console directly in a web browser shows the page. More importantly, is this isolated to my dashboard install? Or will the new update break all the widgets in this repo for everyone. 

Any tips for how to troubleshoot this?

**Comment by jaychen15-zz** [comment]
hmm, this looks like could possibly related to a known issue that we have a KB article. Do you happen to have dual graphic cards in your computer? If you do, please refer to the solution described at http://support.esri.com/technical-article/000012611

**Comment by steffenph** [comment]
Thanks a lot, @jaychen15! Reconfiguring my dual graphics card setup did the trick. All of the custom widgets now work as expected.

PS: Looking forward to the new version of Operations Dashboard:)
